story6app/urls.py
from django.urls import path
from . import views

app_name ="story6app"

urlpatterns = [
    path('landingpage', views.landing_page, name="landingpage"),
    path('landingpage_add', views.landing_page_add_status, name="landingpage_add"),
    path('profile', views.profile, name="profile")
]

story6ppw/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story6app.urls')),
]

story6app/models.py
from django.db import models

# Create your models here.
class Activity(models.Model):
	message = models.CharField(max_length = 800)

story6app/forms.py
from django import forms


class FormStatus(forms.Form):
	status_attrs = {
	    'type':'text',
	    'class':'form-control',
	    'placeholder':'Your Mood',
	}
	message = forms.CharField(max_length = 800, widget = forms.TextInput(attrs = status_attrs), label = "What's Your Mood?")

story6app/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.shortcuts import render, redirect
from .forms import FormStatus
from .models import Activity
from django.http import HttpResponseRedirect

response = {}
# Create your views here.
def landing_page_add_status(request):
	form = FormStatus(request.POST or None)
	if(request.method == 'POST' and form.is_valid()):
	    response['message'] = request.POST['message']
	    activity = Activity(message = response['message'])
	    activity.save()
	    return HttpResponseRedirect('/landingpage')
	else:
	    return HttpResponseRedirect('/landingpage')

	return render(request, 'landingpage.html', response)

def landing_page(request):
	statusq = Activity.objects.all()
	form = FormStatus()
	return render(request, 'landingpage.html', {'form': form, 'statusq': statusq})

def profile(request):
	response = {}
	return render(request, 'profilemela.html', response)

story6app/templates/landingpage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!-- Required meta tags -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <title>Apa Kabar?</title>

    <style>
	body {
		height: 700px;
		background-image: linear-gradient(to left top, #845ec2, #0085e4, #00a2e5, #00b9cc, #00c9a7);
		background-repeat: no-repeat;
		background-size: cover;
	}
	h1 {
		text-align: center;
		color: #280D67;
		font-family: 'Montserrat';
		font-style: normal;
		font-weight: bold;
		font-size: 45px;
		margin-top: 12%;
	}
	.form-group {
		vertical-align: center;
		width: 800px; 
	}
	.box {
		font-family: 'Montserrat';
		position: absolute;
		top: 50%;
		left: 50%;
		-moz-transform: translateX(-50%) translateY(-50%);
		-webkit-transform: translateX(-50%) translateY(-50%);
		transform: translateX(-50%) translateY(-50%);
	}
	.form-group {
		color: #FEFEDF;
	}
	h5{
		font-family: Montserrat;
		color: #280D67;
		text-align: center;
		margin-top: 20%;
	}
	.container {
		width: 500px;
		text-align: center;
		font-family: Montserrat;
		color: #280D67;
		margin-top: 18%;
	}
	.container p{
		text-align: center;
		font-family: Montserrat;
		font-weight: bold;
		font-size: 20px;
	}
	.button {
		text-align: center;
		font-family: Montserrat;
	}
	</style>

</head>
<body>
	<h1>Hello, It's Me. How Are You?</h1>
	<div class = "box">
		<form action="{% url 'story6app:landingpage_add' %}" method="POST">
		<div class="form-group">
			{% csrf_token %}
			{{ form }}
		</div>
		<button type="submit" class="btn btn-primary">Tell It!</button>
	</form>
	</div>

	<div class="container">
		<div class="panel panel-default">
			<div class="panel-body">
				<table style="width:100%">
					{% if statusq %}
						{% for act in statusq %}
						<tr>
							<td>{{ act.message }}</td>
						</tr>
						{% endfor %}
					{% else %}
						<h5>Nothing Here!</h5> 
					{% endif %}
				</table>
				<br> 
				<p>Thank You For Telling Me!</p>
			</div>
		</div>
	</div>

	<div class ="button">
		<button type="button" class="btn btn-outline-light btn-lg">
			<a href="profile" title="See My Profile">My Profile</a>
		</button> 
	</div>
</body>

</html>

story6app/templates/profilemela.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My Profile</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="{% static 'firstjs.js' %}"></script>
</head>
<body>
	<div id="loader">
		<div class="spinner"></div>
	</div>

    <div class="box">
    	<img src="http://mela-ppw.herokuapp.com/foto.png" alt="Khameela Rahmah" class="box-img">
    	<h1>Get to Know Me</h1>
    	<h5>A Computer Science Student</h5>
        <br>
    	<p>Halo Semuanya! Nama saya Khameela Rahmah. Panggil saja Mela. Sekarang saya kuliah di Fakultas Ilmu Komputer Universitas Indonesia. Saya suka mendengarkan musik dan nonton film. Halaman profile ini saya buat sebagai rangkaian dari proses belajar PPW semester ini, Semangat!</p>
        <br>
        <button class="accordion">Activities</button>
        <div class="panel">
            <p>Desain Poster</p>
            <p>Belajar PPW</p>
        </div>
        <button class="accordion">Organizations</button>
        <div class="panel">
            <p>Biro Media BEM Fasilkom UI 2018</p>
            <p>Press COMPFEST X</p>
        </div>
        <button class="accordion">Achievements</button>
        <div class="panel">
            <p>Tepat Waktu</p>
            <p>Bangun Pagi</p>
        </div>
        <br>
        <button id = "daymode" class="btn btn-dark">Change Mood</button>
    </div>
</body>
</html>